<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>imu_publisher</name>
  <version>0.0.0</version>
  <description>IMU Publisher: Interfaces with the IMU sensor to publish orientation and acceleration data.</description>
  <maintainer email="kijong.gong@skyautonet.com">sky</maintainer>
  <license>SkyAutoNet Commercial License</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
