#!/usr/bin/env bash
# SAN v1.5.2 — DCN-2026-011 D-035
# v1.5.3 — DCN-2026-014 v2 (Item 8 + post-review BLOCKERs #3/#4):
#   * write /etc/skyautonet/robot_id per role
#   * symlink network_bringup C++ binary into /usr/local/sbin/
#
# Hardware provisioning for skyautonet systemd services on RK3588.
# Run ONCE per board with sudo. Idempotent — re-run to switch roles.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
    echo "Error: must run with sudo / as root" >&2
    exit 1
fi

ROLES=("leader-go2" "hub-sbc1" "hub-sbc2" "deputy" "follower")
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# colcon install prefix the systemd units expect (see Environment
# WorkingDirectory=/opt/skyautonet in every unit). install.sh assumes
# the workspace was built with --install-base /opt/skyautonet (or
# rsync'd there post-build). Override via SAN_INSTALL_PREFIX.
INSTALL_PREFIX="${SAN_INSTALL_PREFIX:-/opt/skyautonet}"
NETWORK_BRINGUP_SRC="${INSTALL_PREFIX}/lib/san_bringup/network_bringup"
NETWORK_BRINGUP_LINK="/usr/local/sbin/network_bringup"

echo "=== SkyAutoNet RK3588 보드 프로비저닝 (DCN-2026-011 D-035 + DCN-2026-014) ==="
echo
echo "이 보드의 역할을 선택하세요:"
for i in "${!ROLES[@]}"; do
    printf "  %d) %s\n" "$((i+1))" "${ROLES[i]}"
done
echo
read -rp "선택 (1-5): " choice

if ! [[ "${choice}" =~ ^[1-5]$ ]]; then
    echo "Error: 잘못된 선택 '${choice}'" >&2
    exit 1
fi
ROLE="${ROLES[$((choice-1))]}"
SERVICE="skyautonet-${ROLE}.service"
echo "선택된 역할: ${ROLE}"
echo

# 1. robot_id + sbc_id 프로비저닝 — DCN-2026-014 Item 8 (network_bringup)
#    가 두 파일을 모두 읽음. follower 는 4-8 중 하나를 별도 입력.
mkdir -p /etc/skyautonet
case "${ROLE}" in
    leader-go2) ROBOT_ID=1; SBC_ID=0 ;;
    hub-sbc1)   ROBOT_ID=2; SBC_ID=1 ;;
    hub-sbc2)   ROBOT_ID=2; SBC_ID=2 ;;
    deputy)     ROBOT_ID=3; SBC_ID=0 ;;
    follower)
        echo
        echo "Follower slot 을 선택하세요 (4-8):"
        read -rp "robot_id (4|5|6|7|8): " ROBOT_ID
        if ! [[ "${ROBOT_ID}" =~ ^[4-8]$ ]]; then
            echo "Error: follower robot_id 는 4-8 중 하나여야 합니다 '${ROBOT_ID}'" >&2
            exit 1
        fi
        SBC_ID=0
        ;;
esac
echo "${ROBOT_ID}" > /etc/skyautonet/robot_id
echo "${SBC_ID}"   > /etc/skyautonet/sbc_id
chmod 644 /etc/skyautonet/robot_id /etc/skyautonet/sbc_id
echo "  robot_id = ${ROBOT_ID}  (/etc/skyautonet/robot_id)"
echo "  sbc_id   = ${SBC_ID}    (/etc/skyautonet/sbc_id)"

# 2. network_bringup C++ binary symlink — DCN-2026-014 BLOCKER #3/#4.
#    Symlink (not copy) so colcon rebuilds propagate without re-running
#    install.sh. The binary itself ships in /opt/skyautonet/lib/san_bringup/.
if [[ ! -x "${NETWORK_BRINGUP_SRC}" ]]; then
    echo
    echo "Warning: ${NETWORK_BRINGUP_SRC} not found." >&2
    echo "         systemd ExecStartPre will fail until you build + install" >&2
    echo "         the san_bringup package into ${INSTALL_PREFIX} or override" >&2
    echo "         SAN_INSTALL_PREFIX before re-running this script." >&2
else
    ln -sfn "${NETWORK_BRINGUP_SRC}" "${NETWORK_BRINGUP_LINK}"
    echo "  network_bringup -> ${NETWORK_BRINGUP_SRC}  (${NETWORK_BRINGUP_LINK})"
fi

# 3. systemd unit 설치.
SERVICE_PATH="${SCRIPT_DIR}/${SERVICE}"
if [[ ! -f "${SERVICE_PATH}" ]]; then
    echo "Error: ${SERVICE_PATH} 파일을 찾을 수 없습니다" >&2
    exit 1
fi
cp "${SERVICE_PATH}" /etc/systemd/system/
chmod 644 "/etc/systemd/system/${SERVICE}"
echo "  installed /etc/systemd/system/${SERVICE}"

# 3a. follower 는 ROBOT_ID Environment override drop-in (systemd 단위
#     안 ExecStart 가 ${ROBOT_ID} 를 그대로 launch arg 로 전달함).
if [[ "${ROLE}" == "follower" ]]; then
    DROPIN_DIR="/etc/systemd/system/${SERVICE}.d"
    mkdir -p "${DROPIN_DIR}"
    cat > "${DROPIN_DIR}/robot_id.conf" <<EOF
# Auto-generated by install.sh (DCN-2026-014).
[Service]
Environment="ROBOT_ID=${ROBOT_ID}"
EOF
    chmod 644 "${DROPIN_DIR}/robot_id.conf"
    echo "  ${DROPIN_DIR}/robot_id.conf  (ROBOT_ID=${ROBOT_ID})"
fi

# 4. Reload + enable.
systemctl daemon-reload
systemctl enable "${SERVICE}" >/dev/null
echo "  systemctl enable ${SERVICE}  done"

echo
echo "===  프로비저닝 완료  ==="
echo
echo "서비스 시작:"
echo "  sudo systemctl start ${SERVICE}"
echo
echo "상태 확인:"
echo "  sudo systemctl status ${SERVICE}"
echo "  sudo journalctl -u ${SERVICE} -f"
