<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>display</name>
  <version>0.1.0</version>
  <description>OpenGL/EGL/ImGui display node for combat robot visualization</description>
  <maintainer email="kijong.gong@skyautonet.com">sky</maintainer>
  <license>SkyAutoNet Commercial License</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>ament_index_cpp</depend>


  <exec_depend>x11-common</exec_depend>
  <exec_depend>libegl1</exec_depend>
  <exec_depend>libgles2</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
