# CMake generated Testfile for 
# Source directory: /ws/riposte-sw/test
# Build directory: /ws/riposte-sw/build-gz/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(safety_fsm "/ws/riposte-sw/build-gz/test/test_safety_fsm")
set_tests_properties(safety_fsm PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;11;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(seqslot "/ws/riposte-sw/build-gz/test/test_seqslot")
set_tests_properties(seqslot PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;15;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(seeker "/ws/riposte-sw/build-gz/test/test_seeker")
set_tests_properties(seeker PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;25;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(search "/ws/riposte-sw/build-gz/test/test_search")
set_tests_properties(search PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;33;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(modelio "/ws/riposte-sw/build-gz/test/test_modelio")
set_tests_properties(modelio PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;42;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(hailoparse "/ws/riposte-sw/build-gz/test/test_hailoparse")
set_tests_properties(hailoparse PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;51;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(preproc "/ws/riposte-sw/build-gz/test/test_preproc")
set_tests_properties(preproc PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;60;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(assoc "/ws/riposte-sw/build-gz/test/test_assoc")
set_tests_properties(assoc PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;69;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(fusion "/ws/riposte-sw/build-gz/test/test_fusion")
set_tests_properties(fusion PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;80;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(ekf "/ws/riposte-sw/build-gz/test/test_ekf")
set_tests_properties(ekf PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;90;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(imm "/ws/riposte-sw/build-gz/test/test_imm")
set_tests_properties(imm PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;100;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(sizeekf "/ws/riposte-sw/build-gz/test/test_sizeekf")
set_tests_properties(sizeekf PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;109;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(seekerconfig "/ws/riposte-sw/build-gz/test/test_seekerconfig")
set_tests_properties(seekerconfig PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;117;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(motion "/ws/riposte-sw/build-gz/test/test_motion")
set_tests_properties(motion PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;127;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(channelmap "/ws/riposte-sw/build-gz/test/test_channelmap")
set_tests_properties(channelmap PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;135;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(rendezvous "/ws/riposte-sw/build-gz/test/test_rendezvous")
set_tests_properties(rendezvous PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;143;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(guidance "/ws/riposte-sw/build-gz/test/test_guidance")
set_tests_properties(guidance PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;153;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(authz "/ws/riposte-sw/build-gz/test/test_authz")
set_tests_properties(authz PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;160;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(patrol "/ws/riposte-sw/build-gz/test/test_patrol")
set_tests_properties(patrol PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;178;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(camera "/ws/riposte-sw/build-gz/test/test_camera")
set_tests_properties(camera PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;186;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(config "/ws/riposte-sw/build-gz/test/test_config")
set_tests_properties(config PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;191;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(recorder "/ws/riposte-sw/build-gz/test/test_recorder")
set_tests_properties(recorder PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;199;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(attitude "/ws/riposte-sw/build-gz/test/test_attitude")
set_tests_properties(attitude PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;209;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(blackbox "/ws/riposte-sw/build-gz/test/test_blackbox")
set_tests_properties(blackbox PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;214;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
add_test(embedworker "/ws/riposte-sw/build-gz/test/test_embedworker")
set_tests_properties(embedworker PROPERTIES  _BACKTRACE_TRIPLES "/ws/riposte-sw/test/CMakeLists.txt;236;add_test;/ws/riposte-sw/test/CMakeLists.txt;0;")
